### ISSUE TITLE
When config params are not available, the exception reports the field name, not the config value.

### ISSUE THREAD

**Issue by prange** [kantega/reststop#16]
```java
...
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
       at org.kantega.jexmec.ctor.ConstructorInjectionPluginLoader.loadPlugins(ConstructorInjectionPluginLoader.java:64)
       ... 61 more
Caused by: java.lang.IllegalArgumentException: Configuration missing for required @Config field 'datasourceUrl' in class no.bankid.sqldatasource.SqldatasourcePlugin
       at org.kantega.reststop.api.DefaultReststopPlugin.<init>(DefaultReststopPlugin.java:58)
       at no.bankid.sqldatasource.SqldatasourcePlugin.<init>(SqldatasourcePlugin.java:35)
       ... 66 more
```
The field datasourceUrl refers to a config param datasource.url
```
@Config(name="datasource.url") String configUrl
```

**Comment by prange** [comment]
It would be helpful if exceptions related t ocinfiguration would now show stacktraces, but just explain what is wrong, and how it might be fixed. (for example where it expects the config do be)
