### ISSUE TITLE
/assets/metrics yields NullPointerException

### ISSUE THREAD

**Issue by prange** [kantega/reststop#2]
When doing a fresh install of the example app, the url /assets/metrics shows a stacktrace for a NPE:

```
HTTP ERROR 500

Problem accessing /assets/metrics. Reason:

    Server Error
Caused by:

java.lang.NullPointerException
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.kantega.reststop.core.ReststopInitializer$AssetFilter.copy(ReststopInitializer.java:739)
	at org.kantega.reststop.core.ReststopInitializer$AssetFilter.doFilter(ReststopInitializer.java:727)
	at org.kantega.reststop.core.ReststopInitializer$MappingWrappedFilter.doFilter(ReststopInitializer.java:485)
	at org.kantega.reststop.core.ReststopInitializer$PluginFilterChain.doFilter(ReststopInitializer.java:585)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:548)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:482)
	at org.kantega.reststop.jaxrs.JerseyPlugin$2.doFilter(JerseyPlugin.java:82)
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:419)
	at org.kantega.reststop.core.ReststopInitializer$MappingWrappedFilter.doFilter(ReststopInitializer.java:485)
	at org.kantega.reststop.core.ReststopInitializer$PluginFilterChain.doFilter(ReststopInitializer.java:585)
	at org.kantega.reststop.development.RedeployFilter.doFilter(RedeployFilter.java:62)
	at org.kantega.reststop.core.ReststopInitializer$MappingWrappedFilter.doFilter(ReststopInitializer.java:485)
	at org.kantega.reststop.core.ReststopInitializer$PluginFilterChain.doFilter(ReststopInitializer.java:585)
	at org.kantega.reststop.core.ReststopInitializer$PluginDelegatingFilter.doFilter(ReststopInitializer.java:520)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.NullPointerException
		at java.io.FilterInputStream.close(FilterInputStream.java:181)
		at sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream.close(JarURLConnection.java:108)
		at org.kantega.reststop.core.ReststopInitializer$AssetFilter.doFilter(ReststopInitializer.java:728)
		... 32 more
Powered by Jetty://

```

**Comment by espenaf** [comment]
This change breaks fetching of normal assets on source path. They will now all be redirected to path+ /, as they get catched by: 

<code>
if(resource != null && !path.endsWith("/") && loader.getResource(path +"/") != null )
</code>

**Comment by eirbjo** [comment]
Thanks to @espenaf for pointing this out. Turns out fixing "is directory" testing for jar URLs broke file URLs. So I extracted the logic into a method isDirectoryResource. This method has independent code paths for each URL protocol case so it should be more readable and robust. So hopefully this regression won't happen again :-)

**Comment by eirbjo** [comment]
@espenaf Would you mind testing this issue again and then close if it works for you?
