### ISSUE TITLE
Error when depending on Metrics-plugin 

### ISSUE THREAD

**Issue by prange** [kantega/reststop#6]
```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of java/net/URLClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:336)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:305)
    at com.codahale.metrics.jvm.BufferPoolMetricSet.<clinit>(BufferPoolMetricSet.java:24)
    at org.kantega.reststop.metrics.MetricsReststopPlugin.initMetricsRegistry(MetricsReststopPlugin.java:85)
    at org.kantega.reststop.metrics.MetricsReststopPlugin.<init>(MetricsReststopPlugin.java:38)
    ... 59 more
```

**Comment by eirbjo** [comment]
You have SLF4J APIs and implementation jars both in your WebappClassLoader and in your child plugin class loaders. 

You have to choose. And you probably only want logging to be configured on the application level. So make sure you don't add slf4j (or logback) classes on any plugin. 

You'll find a list of plugin class loader class paths on http://localhost:8085/dev
